version: 2
before:
  hooks:
    - bash .goreleaser-hook-before.sh {{ .Version }}
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
      - arm64
    goamd64:
      - v3
    flags:
      - -v
      - -trimpath
    ldflags:
      - -s
      - -w
      - -H=windowsgui
    mod_timestamp: '{{ .CommitTimestamp }}'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  draft: false
  prerelease: auto
  extra_files:
    - glob: example-code-signing*
archives:
  - formats:
      - none
checksum:
  algorithm: sha256
nfpms:
  - formats: [msix]
    maintainer: Rui Lopes <rgl@example.com>
    homepage: https://github.com/rgl/example-go-windows-app
    contents:
      - src: gopher.png
        dst: gopher.png
    msix:
      publisher: "CN=example.com"
      properties:
        display_name: Example Go Windows App
        logo: gopher.png # see https://thesvg.org/icon/gopher
      applications:
        - id: ExampleGoWindowsApp
          executable: example-go-windows-app.exe
      signature:
        pfx_file: example-code-signing.p12
